#!/usr/bin/env ruby
# Read content of file moons.csv, containing the coordinates of a point on a 2D
# plane and the respective label into a data structure
require 'csv'
require 'maurograd/scalar'

def batches(inputs, labels, batch_size)
  idx = (0...inputs.length).to_a.shuffle
  idx.each_slice(batch_size).map do |sl|
    [sl.map { |i| inputs[i] }, sl.map { |i| labels[i] }]
  end
end

dataset = CSV.read("moons.csv", headers: true)

# Create a neural network to predict the label of a point based on its coordinates
# mlp = Maurograd::Scalar::MLP.new(layer_sizes: [2, 5, 5, 1])
mlp = Maurograd::Scalar::MLP.new(layer_sizes: [2, 15, 13, 7, 1])

# Divide the data into training and test sets: 80% for training and 20% for testing dataset
train_set = { inputs: [], labels: [] }
test_set = { inputs: [], labels: [] }
dataset.each_with_index do |row, i|
  if i % 5 == 0
    test_set[:inputs] << [row[0].to_f, row[1].to_f]
    test_set[:labels] << row[2].to_f
  else
    train_set[:inputs] << [row[0].to_f, row[1].to_f]
    train_set[:labels] << row[2].to_f
  end
end

epochs = 50
batch_size = 32
lr = 0.05
eps = 1e-8

# Train the neural network on the training set
epochs.times do |i|
  puts "\n********** EPOCH #{i+1} **********"

  losses = []

  batch_number = 0
  batches(train_set[:inputs], train_set[:labels], batch_size).each do |bx, by|
    batch_number += 1
    puts "Batch #{batch_number}" if (batch_number % 10).zero?

    ps = bx.map { |x| mlp.call(inputs: x).sigmoid }

    # BCE averaged over the batch
    bce_terms = ps.each_with_index.map do |p, j|
      y = by[j]                                   # y in {0.0, 1.0} (labels are already floats)
      term1 = (p + eps).log * (-y)                # - y * log(p + eps)
      term2 = (1.0 - p + eps).log * (-(1.0 - y))  # - (1 - y) * log(1 - p + eps)
      term1 + term2
    end

    loss = bce_terms.reduce { |a, b| a + b } * (1.0 / bce_terms.length)

    # First, set all of the parameter gradients to 0 so that we don't accumulate
    # gradients from previous iterations
    loss.zero_grad!

    # Backpropagate the loss to compute gradients
    loss.backpropagate

    losses << loss.data

    # update weights
    mlp.parameters.each { |param| param.data += -lr * param.gradient }

    # gmean = mlp.parameters.map { |p| p.gradient.abs }.sum / mlp.parameters.length.to_f
    # puts "gmean=#{gmean}"  # should be > 0 and not blow up
  end

  puts "Average loss within this epoch: #{losses.sum / losses.length}"
end

# Evaluate the neural network on the test set
puts "\nPredictions vs Actual on first 11 test samples:"
probs = test_set[:inputs].first(11).map { |x| mlp.call(inputs: x).sigmoid }
predictions = probs.map { |p| (p.data >= 0.5) ? 1 : 0 }
actual = test_set[:labels].first(11).map(&:to_i)
puts "Predictions on test set: #{predictions}"
puts "Actual labels on test set: #{actual}"


# Overall accuracy on the whole test set
puts "\nEvaluating on the entire test set..."
all_probs = test_set[:inputs].map { |x| mlp.call(inputs: x).sigmoid.data }
all_pred  = all_probs.map { |p| p >= 0.5 ? 1 : 0 }
acc = all_pred.zip(test_set[:labels].map(&:to_i)).count { |a,b| a == b }.fdiv(test_set[:labels].length)
puts "Test accuracy: #{(100*acc).round(2)}%"
